name: client_2
description: app for client #2
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  #local packages (located in packages folder)
  data: ^0.1.0+1
  domain: ^0.1.0+1
  resources: ^0.1.0+1
  shared_ui: ^0.1.0+1
  utilities: ^0.1.0+1

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
