name: initializer
description: initializer package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  injectable: ^2.3.2
  get_it: ^7.6.4
  json_annotation: ^4.8.1
  fpdart: ^1.1.0

  #local packages (located in packages folder)
  data: ^0.1.0+1
  domain: ^0.1.0+1
  shared: ^0.1.0+1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  injectable_generator: ^2.4.1
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.0
