name: client_1
description: app for client #1
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.3.2
  intl: ^0.18.0
  get_it: ^7.6.4
  shimmer: ^3.0.0
  fpdart: ^1.1.0
  bloc_concurrency: ^0.2.2
  stream_transform: ^2.1.0

  #local packages (located in packages folder)
  domain: ^0.1.0+1
  resources: ^0.1.0+1
  shared: ^0.1.0+1
  utilities: ^0.1.0+1

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  injectable_generator: ^2.4.1
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
